nginx-ingress:
  controller:
    image:
      repository: aditidoc/nginxplus
      tag: 1.11.4
    #config:
      #entries: { proxy-protocol: "True" ,real-ip-header: "proxy_protocol",set-real-ip-from: "0.0.0.0/0"}
    service:
      type: NodePort
      customports: [{port: 8081, name: readiness-port, protocol: TCP}]
