nginx-ingress:
  controller:
    nginxplus: true
    image:
      repository: aditidoc/kic
      tag: 2.0.3-SNAPSHOT-66e69fe
    config:
      entries: { proxy-protocol: "True" ,real-ip-header: "proxy_protocol",set-real-ip-from: "0.0.0.0/0"}
    service:
      type: NodePort
    #  extraLabels: {cis.f5.com/as3-tenant: Nginx_IC, cis.f5.com/as3-app: Nginx_IC_vs , cis.f5.com/as3-pool: Nginx_IC_pool}
    #  customports: [{port: 8081, name: readiness-port, protocol: TCP}]
    enableSnippets: true
