nginx-ingress:
  prometheus:
    service:
      create: true
  controller:
   # config:
   #   entries:
   #     proxy-protocol: "True"
   #     real-ip-header: "proxy_protocol"
   #     set-real-ip-from: "0.0.0.0/0"
    nginxplus: true
    image:
      repository: aditidoc/nginx-plus-ingress
      tag: 3.6.1-SNAPSHOT
    config:
      #entries: { proxy-protocol: "True" ,real-ip-header: "proxy_protocol",set-real-ip-from: "0.0.0.0/0"}
      entries: {resolver-addresses: "8.8.8.8"}
    service:
      type: NodePort
      #extraLabels: { app: ingresslink }
      #extraLabels: {cis.f5.com/as3-tenant: Nginx_IC, cis.f5.com/as3-app: Nginx_IC_vs , cis.f5.com/as3-pool: Nginx_IC_pool}
      #extraLabels: {cis.f5.com/as3-tenant: vcptoisp002l, cis.f5.com/as3-app: vcptoisp002l_vs , cis.f5.com/as3-pool: vcptoisp002l_pool}
      #customPorts: [{name: readiness-port,port: 8081, protocol: TCP}]
    #reportIngressStatus:
    #  enable: true
    #  ingressLink: "ingresslink"
    enableSnippets: true
