apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: f5-cis
  namespace: openshift-gitops
spec:
  destination:
    namespace: f5-cis
    server: https://kubernetes.default.svc
  project: default
  source:
    path: f5-cis-subchart/
    repoURL: https://github.com/aditinet/devops
    targetRevision: main
  sync:
    comparedTo:
      destination:
        namespace: f5-cis
        server: https://kubernetes.default.svc
      source:
        path: f5-cis-subchart/
        repoURL: https://github.com/aditinet/devops
        targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
