apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcgw-subchart
  namespace: openshift-gitops
spec:
  destination:
    namespace: mcgw
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mcgw-subchart/
    repoURL: https://github.com/aditinet/devops
    targetRevision: main
  sync:
    comparedTo:
      destination:
        namespace: mcgw
        server: https://kubernetes.default.svc
      source:
        path: mcgw-subchart/
        repoURL: https://github.com/aditinet/devops
        targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
